export const landmarkList = [
    {
        name: "BYU-I Sign",
        description: "The iconic 8-foot-tall blue BYU-I letters unveiled in 2024. Kiss in the 'U' for good luck — it's already a campus tradition!",
        longitude: -111.78337921743216,
        latitude: 43.817702355970624,
    },
    {
        name: "Rexburg Idaho Temple",
        description: "A stunning 169-foot single-spire temple sitting on 10 acres just south of campus. The public gardens to the west are open to all.",
        longitude: -111.77908800,
        latitude: 43.81070900,
    },
    {
        name: "Temple Gardens",
        description: "The peaceful public garden west of the Rexburg Temple. A favorite spot for picnics, photos, and quiet reflection.",
        longitude: -111.78050,
        latitude: 43.81090,
    },
    {
        name: "Rexburg Stake Tabernacle",
        description: "A historic 1911 landmark on the National Register of Historic Places. Home to the Museum of Rexburg and the Teton Flood Exhibit in its basement.",
        longitude: -111.78361,
        latitude: 43.82750,
    },
    {
        name: "Museum of Rexburg / Teton Flood Exhibit",
        description: "Learn about the catastrophic 1976 Teton Dam collapse that left Rexburg underwater. Includes a guided tour, video presentation, and children's activities.",
        longitude: -111.78361,
        latitude: 43.82750,
    },
    {
        name: "Idaho Centennial Carousel",
        description: "The only antique wooden carousel in Idaho, lovingly restored and dating back to 1926. Located in Porter Park — rides are cheap and the nostalgia is free.",
        longitude: -111.79440,
        latitude: 43.82300,
    },
    {
        name: "Porter Park",
        description: "Rexburg's oldest municipal park, established in 1929. Features the Centennial Carousel, picnic tables, tennis, volleyball, and basketball courts.",
        longitude: -111.79440,
        latitude: 43.82270,
    },
    {
        name: "Rexburg Rapids",
        description: "The city's own waterpark with water slides, a lazy river, splash climbing wall, and a kids' play area. Open summers only, with student discounts!",
        longitude: -111.78750,
        latitude: 43.83100,
    },
    {
        name: "Rexburg Nature Park",
        description: "A peaceful retreat along the South Fork of the Teton River with ponds, walking trails, a skate park, and great birdwatching.",
        longitude: -111.80300,
        latitude: 43.83200,
    },
    {
        name: "Legacy Flight Museum",
        description: "A hangar packed with historic military aircraft — many still flyable! Sit in a MASH helicopter, climb into cockpits, and hear stories from a former Navy pilot.",
        longitude: -111.80670,
        latitude: 43.83460,
    },
    {
        name: "Yellowstone Bear World",
        description: "A drive-through wildlife park just 5 miles south of Rexburg on US-20. See grizzlies, elk, bison, and moose from your car — and bottle-feed bear cubs in season!",
        longitude: -111.86583,
        latitude: 43.73889,
    },
    {
        name: "St. Anthony Sand Dunes",
        description: "About 20 miles north of Rexburg, these vast white sand dunes are a playground for OHVs, sandboarding, and stunning desert sunsets.",
        longitude: -111.79494,
        latitude: 44.00373,
    },
    {
        name: "Cress Creek Nature Trail",
        description: "A scenic ADA-accessible paved trail with overlooks above the Snake River canyon. The sunset views from the observation points are spectacular.",
        longitude: -111.68500,
        latitude: 43.84800,
    },
    {
        name: "Teton River",
        description: "The river that runs through northern Rexburg — and the one that flooded it in 1976. A beautiful spot for fishing, floating, and wildlife spotting.",
        longitude: -111.80000,
        latitude: 43.84000,
    },
    {
        name: "Madison County Courthouse",
        description: "A handsome historic courthouse in downtown Rexburg. A classic slice of small-town Idaho architecture right in the heart of the city.",
        longitude: -111.78389,
        latitude: 43.82600,
    },
    {
        name: "Hemming Village",
        description: "An inner-city hub for local shopping, dining, and art. The Hemming Village Art Gallery showcases paintings, sculptures, and works from local artists.",
        longitude: -111.78500,
        latitude: 43.82400,
    },
    {
        name: "BYU-Idaho Ropes Course",
        description: "A free outdoor ropes course just south of campus open to BYU-I students. Test your balance and nerve while making friends — or enemies.",
        longitude: -111.78400,
        latitude: 43.81500,
    },
    {
        name: "BYU-Idaho Orchard",
        description: "Pick your own apples each fall from BYU-I's own orchard. Goes hand-in-hand with the Annual Apple Blossom Festival each spring.",
        longitude: -111.78600,
        latitude: 43.81400,
    },
    {
        name: "Porter Park Skate Park",
        description: "A local skate park tucked into Porter Park. A popular hangout for students looking to shred or just watch people shred.",
        longitude: -111.79500,
        latitude: 43.82350,
    },
    {
        name: "Riverside Park / Community Gardens",
        description: "Part of Rexburg's Teton River Corridor trail system. Home to community garden plots, a BMX dirt track, and playing fields.",
        longitude: -111.78750,
        latitude: 43.83200,
    },
    {
        name: "Rexburg–Madison County Airport",
        description: "A small regional airport that doubles as the backdrop for the Legacy Flight Museum airshows. Keep an eye out for vintage planes in the sky!",
        longitude: -111.80500,
        latitude: 43.83500,
    },
    {
        name: "G's Dairy",
        description: "Rexburg's beloved local creamery and a rite of passage for every BYU-I student. Famous for huge, fresh ice cream cones at unbeatable prices.",
        longitude: -111.79100,
        latitude: 43.82100,
    },
    {
        name: "Big Jud's Burgers",
        description: "A Rexburg institution known for absurdly large burgers. Finish one alone and your name goes on the wall. A must-do.",
        longitude: -111.78900,
        latitude: 43.82200,
    },
    {
        name: "Smith Park",
        description: "A neighborhood park in Rexburg with open green space, a playground, and a relaxed atmosphere — great for a low-key afternoon.",
        longitude: -111.78200,
        latitude: 43.83000,
    },
    {
        name: "Teton Dam Site",
        description: "About 20 miles northeast of Rexburg off SR-33, you can visit the remnants of the Teton Dam that catastrophically failed in 1976. A sobering and fascinating piece of local history.",
        longitude: -111.53000,
        latitude: 43.92000,
    },
];